@file:OptIn(kotlin.ExperimentalUnsignedTypes::class)

package com.boltffi.demo

import java.net.URI
import java.time.Duration
import java.time.Instant
import java.util.UUID
import kotlin.math.PI
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertIs
import kotlin.test.assertNull
import kotlin.test.assertTrue

class DemoValueTypesTest {
    @Test
    fun builtinsAndCustomTypesRoundTrip() {
        val duration = Duration.ofSeconds(2).plusMillis(500)
        demoCase("case:builtins.duration.should_roundtrip_value")
        assertEquals(duration, echoDuration(duration))
        demoCase("case:builtins.duration.should_construct_from_parts")
        assertEquals(Duration.ofSeconds(3).plusNanos(25), makeDuration(3uL, 25u))
        demoCase("case:builtins.duration.should_report_milliseconds")
        assertEquals(2_500uL, durationAsMillis(duration))

        val instant = Instant.ofEpochMilli(1_701_234_567_890L)
        demoCase("case:builtins.system_time.should_roundtrip_value")
        assertEquals(instant, echoSystemTime(instant))
        demoCase("case:builtins.system_time.should_roundtrip_pre_epoch_value")
        val preEpoch = Instant.ofEpochSecond(-1, 500_000_000)
        assertEquals(preEpoch, echoSystemTime(preEpoch))
        demoCase("case:builtins.system_time.should_convert_to_epoch_milliseconds")
        assertEquals(1_701_234_567_890uL, systemTimeToMillis(instant))
        demoCase("case:builtins.system_time.should_construct_from_epoch_milliseconds")
        assertEquals(instant, millisToSystemTime(1_701_234_567_890uL))

        val uuid = UUID.fromString("123e4567-e89b-12d3-a456-426614174000")
        demoCase("case:builtins.uuid.should_roundtrip_value")
        assertEquals(uuid, echoUuid(uuid))
        demoCase("case:builtins.uuid.should_format_canonical_string")
        assertEquals(uuid.toString(), uuidToString(uuid))

        val url = URI("https://example.com/demo?q=boltffi")
        demoCase("case:builtins.url.should_roundtrip_value")
        assertEquals(url, echoUrl(url))
        demoCase("case:builtins.url.should_format_string")
        assertEquals(url.toString(), urlToString(url))

        val email = "café@example.com"
        demoCase("case:custom_types.email.should_roundtrip_value")
        assertEquals(email, echoEmail(email))
        demoCase("case:custom_types.email.should_extract_domain")
        assertEquals("example.com", emailDomain(email))

        val datetime: UtcDateTime = 1_701_234_567_890L
        demoCase("case:custom_types.datetime.should_roundtrip_millis")
        assertEquals(datetime, echoDatetime(datetime))
        demoCase("case:custom_types.datetime.should_convert_to_millis")
        assertEquals(1_701_234_567_890L, datetimeToMillis(datetime))
        demoCase("case:custom_types.datetime.should_format_rfc3339_timestamp")
        assertEquals("2023-11-29T05:09:27.890+00:00", formatTimestamp(datetime))

        val event = Event("kotlin-launch", datetime)
        demoCase("case:custom_types.event.should_expose_datetime_field")
        assertEquals(datetime, event.timestamp)
        demoCase("case:custom_types.event.should_roundtrip_datetime_field")
        assertEquals(event, echoEvent(event))
        demoCase("case:custom_types.event.should_extract_timestamp_millis")
        assertEquals(datetime, eventTimestamp(event))

        val emails = listOf("café@example.com", "user@example.org")
        demoCase("case:custom_types.vectors.emails.should_roundtrip_values")
        assertContentEquals(emails, echoEmails(emails))

        val datetimes = listOf<Long>(1_710_000_000_000L, 1_710_000_001_000L, 1_710_000_002_000L)
        demoCase("case:custom_types.vectors.datetimes.should_roundtrip_millis_values")
        assertContentEquals(datetimes, echoDatetimes(datetimes))
    }

    @Test
    fun primitivesStringsBytesAndVectorsRoundTrip() {
        assertEquals(true, echoBool(true), "case:primitives.scalars.bool.should_roundtrip_true")
        assertEquals(true, negateBool(false), "case:primitives.scalars.bool.should_negate_false_to_true")
        assertEquals((-7).toByte(), echoI8((-7).toByte()), "case:primitives.scalars.i8.should_roundtrip_negative_value")
        assertEquals(255u.toUByte(), echoU8(255u.toUByte()), "case:primitives.scalars.u8.should_roundtrip_max_value")
        assertEquals((-1234).toShort(), echoI16((-1234).toShort()), "case:primitives.scalars.i16.should_roundtrip_negative_value")
        assertEquals(55_000u.toUShort(), echoU16(55_000u.toUShort()), "case:primitives.scalars.u16.should_roundtrip_large_value")
        assertEquals(-42, echoI32(-42), "case:primitives.scalars.i32.should_roundtrip_negative_value")
        assertEquals(30, addI32(10, 20), "case:primitives.scalars.i32.should_add_two_values")
        assertEquals(4_000_000_000u, echoU32(4_000_000_000u), "case:primitives.scalars.u32.should_roundtrip_large_value")
        assertEquals(-9_999_999_999L, echoI64(-9_999_999_999L), "case:primitives.scalars.i64.should_roundtrip_large_negative_value")
        assertEquals(9_999_999_999uL, echoU64(9_999_999_999uL), "case:primitives.scalars.u64.should_roundtrip_large_value")
        demoCase("case:primitives.scalars.f32.should_roundtrip_value_with_tolerance")
        assertFloatEquals(3.5f, echoF32(3.5f))
        demoCase("case:primitives.scalars.f32.should_add_two_values_with_tolerance")
        assertFloatEquals(4.0f, addF32(1.5f, 2.5f))
        demoCase("case:primitives.scalars.f64.should_roundtrip_pi_with_tolerance")
        assertDoubleEquals(3.14159265359, echoF64(3.14159265359))
        demoCase("case:primitives.scalars.f64.should_add_two_values_with_tolerance")
        assertDoubleEquals(4.0, addF64(1.5, 2.5))
        assertEquals(123uL, echoUsize(123uL), "case:primitives.scalars.usize.should_roundtrip_value")
        assertEquals(-123L, echoIsize(-123L), "case:primitives.scalars.isize.should_roundtrip_negative_value")
        demoCase("case:primitives.scalars.noop.should_cross_without_values")
        noop()
        demoCase("case:primitives.scalars.i32.should_add_with_benchmark_alias")
        assertEquals(7, add(3, 4))
        demoCase("case:primitives.scalars.f64.should_multiply_two_values")
        assertDoubleEquals(6.0, multiply(2.0, 3.0))

        assertEquals("", echoString(""), "case:primitives.strings.string.should_roundtrip_empty")
        assertEquals("hello 🌍", echoString("hello 🌍"), "case:primitives.strings.string.should_roundtrip_emoji")
        assertEquals("foobar", concatStrings("foo", "bar"), "case:primitives.strings.string.should_concatenate_values")
        assertEquals(5u, stringLength("café"), "case:primitives.strings.string.should_report_utf8_byte_length")
        assertEquals(true, stringIsEmpty(""), "case:primitives.strings.string.should_detect_empty")
        assertEquals("ababab", repeatString("ab", 3u), "case:primitives.strings.string.should_repeat_value")
        assertEquals("borrowed static", borrowedStaticString(), "case:primitives.strings.borrowed_static_string.should_return_value")

        assertContentEquals(byteArrayOf(1, 2, 3, 4), echoBytes(byteArrayOf(1, 2, 3, 4)), "case:bytes.bytes.should_roundtrip_values")
        assertEquals(3u, bytesLength(byteArrayOf(9, 8, 7)), "case:bytes.bytes.should_report_length")
        assertEquals(10u, bytesSum(byteArrayOf(1, 2, 3, 4)), "case:bytes.bytes.should_sum_values")
        assertContentEquals(byteArrayOf(0, 1, 2, 3), makeBytes(4u), "case:bytes.bytes.should_make_sequential_values")
        assertContentEquals(byteArrayOf(4, 3, 2, 1), reverseBytes(byteArrayOf(1, 2, 3, 4)), "case:bytes.bytes.should_reverse_values")

        assertContentEquals(intArrayOf(1, 2, 3), echoVecI32(intArrayOf(1, 2, 3)), "case:primitives.vecs.i32.should_roundtrip_non_empty")
        assertContentEquals(intArrayOf(), echoVecI32(intArrayOf()), "case:primitives.vecs.i32.should_roundtrip_empty")
        assertContentEquals(byteArrayOf(-1, 0, 7), echoVecI8(byteArrayOf(-1, 0, 7)), "case:primitives.vecs.i8.should_roundtrip_values")
        assertContentEquals(byteArrayOf(0, 1, 2, 3), echoVecU8(byteArrayOf(0, 1, 2, 3)), "case:primitives.vecs.u8.should_roundtrip_values")
        assertContentEquals(shortArrayOf(-3, 0, 9), echoVecI16(shortArrayOf(-3, 0, 9)), "case:primitives.vecs.i16.should_roundtrip_values")
        assertContentEquals(ushortArrayOf(0u, 10u, 20u), echoVecU16(ushortArrayOf(0u, 10u, 20u)), "case:primitives.vecs.u16.should_roundtrip_values")
        assertContentEquals(uintArrayOf(0u, 10u, 20u), echoVecU32(uintArrayOf(0u, 10u, 20u)), "case:primitives.vecs.u32.should_roundtrip_values")
        assertContentEquals(longArrayOf(-5L, 0L, 8L), echoVecI64(longArrayOf(-5L, 0L, 8L)), "case:primitives.vecs.i64.should_roundtrip_values")
        assertContentEquals(ulongArrayOf(0uL, 1uL, 2uL), echoVecU64(ulongArrayOf(0uL, 1uL, 2uL)), "case:primitives.vecs.u64.should_roundtrip_values")
        assertContentEquals(longArrayOf(-2L, 0L, 5L), echoVecIsize(longArrayOf(-2L, 0L, 5L)), "case:primitives.vecs.isize.should_roundtrip_values")
        assertContentEquals(ulongArrayOf(0uL, 2uL, 4uL), echoVecUsize(ulongArrayOf(0uL, 2uL, 4uL)), "case:primitives.vecs.usize.should_roundtrip_values")
        assertContentEquals(floatArrayOf(1.25f, -2.5f), echoVecF32(floatArrayOf(1.25f, -2.5f)), "case:primitives.vecs.f32.should_roundtrip_values_with_tolerance")
        assertContentEquals(doubleArrayOf(1.5, 2.5), echoVecF64(doubleArrayOf(1.5, 2.5)), "case:primitives.vecs.f64.should_roundtrip_values")
        assertContentEquals(booleanArrayOf(true, false, true), echoVecBool(booleanArrayOf(true, false, true)), "case:primitives.vecs.bool.should_roundtrip_values")
        assertContentEquals(listOf("hello", "world"), echoVecString(listOf("hello", "world")), "case:primitives.vecs.string.should_roundtrip_values")
        assertContentEquals(uintArrayOf(2u, 5u), vecStringLengths(listOf("hi", "café")), "case:primitives.vecs.string.should_report_utf8_byte_lengths")
        assertEquals(60L, sumVecI32(intArrayOf(10, 20, 30)), "case:primitives.vecs.i32.should_sum_values")
        assertContentEquals(intArrayOf(0, 1, 2, 3, 4), makeRange(0, 5), "case:primitives.vecs.i32.should_make_range")
        assertContentEquals(intArrayOf(3, 2, 1), reverseVecI32(intArrayOf(1, 2, 3)), "case:primitives.vecs.i32.should_reverse_values")
        demoCase("case:primitives.vecs.i32.should_generate_sequence")
        assertContentEquals(intArrayOf(0, 1, 2, 3), generateI32Vec(4))
        demoCase("case:primitives.vecs.i32.should_sum_benchmark_values")
        assertEquals(10L, sumI32Vec(intArrayOf(1, 2, 3, 4)))
        demoCase("case:primitives.vecs.f64.should_generate_sequence")
        assertContentEquals(doubleArrayOf(0.0, 0.1, 0.2), generateF64Vec(3))
        demoCase("case:primitives.vecs.f64.should_sum_values")
        assertDoubleEquals(7.5, sumF64Vec(doubleArrayOf(1.5, 2.5, 3.5)))

        val u64Values = ulongArrayOf(5uL, 9uL, 11uL)
        demoCase("case:primitives.vecs.u64.should_increment_first_value_in_place")
        incU64(u64Values)
        assertEquals(6uL, u64Values[0])
        demoCase("case:primitives.vecs.u64.should_increment_value")
        assertEquals(43uL, incU64Value(42uL))
    }

    @Test
    fun nestedVecsRoundTrip() {
        val input = listOf(intArrayOf(1, 2, 3), intArrayOf(), intArrayOf(4, 5))
        demoCase("case:primitives.vecs.nested_i32.should_roundtrip_values")
        val roundTripped = echoVecVecI32(input)
        assertEquals(input.size, roundTripped.size)
        for (i in input.indices) {
            assertContentEquals(input[i], roundTripped[i])
        }
        demoCase("case:primitives.vecs.nested_i32.should_roundtrip_empty_outer")
        assertEquals(0, echoVecVecI32(emptyList()).size)

        val bools = listOf(booleanArrayOf(true, false, true), booleanArrayOf(), booleanArrayOf(false))
        demoCase("case:primitives.vecs.nested_bool.should_roundtrip_values")
        val roundTrippedBools = echoVecVecBool(bools)
        assertEquals(bools.size, roundTrippedBools.size)
        for (i in bools.indices) {
            assertContentEquals(bools[i], roundTrippedBools[i])
        }

        val isizes = listOf(longArrayOf(-2L, 0L, 5L), longArrayOf(), longArrayOf(9L))
        demoCase("case:primitives.vecs.nested_isize.should_roundtrip_values")
        val roundTrippedIsizes = echoVecVecIsize(isizes)
        assertEquals(isizes.size, roundTrippedIsizes.size)
        for (i in isizes.indices) {
            assertContentEquals(isizes[i], roundTrippedIsizes[i])
        }

        val usizes = listOf(ulongArrayOf(0uL, 2uL, 4uL), ulongArrayOf(), ulongArrayOf(8uL))
        demoCase("case:primitives.vecs.nested_usize.should_roundtrip_values")
        val roundTrippedUsizes = echoVecVecUsize(usizes)
        assertEquals(usizes.size, roundTrippedUsizes.size)
        for (i in usizes.indices) {
            assertContentEquals(usizes[i], roundTrippedUsizes[i])
        }

        val strings = listOf(listOf("hello", "world"), emptyList(), listOf("café", "🌍"))
        demoCase("case:primitives.vecs.nested_string.should_roundtrip_utf8_values")
        assertEquals(strings, echoVecVecString(strings))

        demoCase("case:primitives.vecs.nested_i32.should_flatten_values")
        assertContentEquals(
            intArrayOf(1, 2, 3, 4, 5),
            flattenVecVecI32(listOf(intArrayOf(1, 2), intArrayOf(3), intArrayOf(), intArrayOf(4, 5))),
        )
        demoCase("case:primitives.vecs.nested_i32.should_flatten_empty")
        assertContentEquals(intArrayOf(), flattenVecVecI32(emptyList()))
    }

    @Test
    fun blittableRecordVecsRoundTrip() {
        demoCase("case:records.blittable.locations.should_generate_sample_vector")
        val locations = generateLocations(3)
        assertEquals(3, locations.size)
        demoCase("case:records.blittable.locations.should_count_vector_items")
        assertEquals(3, processLocations(locations))
        demoCase("case:records.blittable.locations.should_sum_generated_ratings")
        assertDoubleEquals(9.3, sumRatings(locations))
        demoCase("case:records.blittable.locations.should_count_empty_vector")
        assertEquals(0, processLocations(emptyList()))

        val hostLocations = listOf(
            Location(1L, 10.0, 20.0, 4.0, 5, true),
            Location(2L, 11.0, 21.0, 4.5, 6, false),
        )
        demoCase("case:records.blittable.locations.should_count_host_constructed_vector")
        assertEquals(2, processLocations(hostLocations))
        demoCase("case:records.blittable.locations.should_sum_host_constructed_ratings")
        assertDoubleEquals(8.5, sumRatings(hostLocations))

        demoCase("case:records.blittable.locations.find_location.should_return_some_for_positive_id")
        val foundLocation = findLocation(5)
        assertEquals(5L, foundLocation?.id)
        assertEquals(true, foundLocation?.isOpen)
        demoCase("case:records.blittable.locations.find_location.should_return_none_for_non_positive_id")
        assertNull(findLocation(0))
        demoCase("case:records.blittable.locations.find_locations.should_return_some_vector_for_positive_count")
        assertEquals(3, findLocations(3)?.size)
        demoCase("case:records.blittable.locations.find_locations.should_return_none_for_non_positive_count")
        assertNull(findLocations(-1))

        demoCase("case:records.blittable.trades.should_generate_sample_vector")
        val trades = generateTrades(3)
        assertEquals(3, trades.size)
        demoCase("case:records.blittable.trades.should_sum_volumes")
        assertEquals(3000L, sumTradeVolumes(trades))
        demoCase("case:records.blittable.trades.should_aggregate_with_locations")
        assertEquals(3002L, aggregateLocationTradeStats(locations, trades))

        demoCase("case:records.blittable.particles.should_generate_sample_vector")
        val particles = generateParticles(3)
        assertEquals(3, particles.size)
        demoCase("case:records.blittable.particles.should_sum_masses")
        assertDoubleEquals(3.003, sumParticleMasses(particles))

        demoCase("case:records.blittable.sensor_readings.should_generate_sample_vector")
        val readings = generateSensorReadings(3)
        assertEquals(3, readings.size)
        demoCase("case:records.blittable.sensor_readings.should_average_generated_temperatures")
        assertDoubleEquals(21.0, avgSensorTemperature(readings))
        demoCase("case:records.blittable.sensor_readings.should_average_empty_vector_as_zero")
        assertDoubleEquals(0.0, avgSensorTemperature(emptyList()))
    }

    @Test
    fun optionFunctionsUseCorrectKotlinSurface() {
        demoCase("case:options.primitives.i32.should_roundtrip_some")
        assertEquals(7, echoOptionalI32(7))
        demoCase("case:options.primitives.i32.should_roundtrip_none")
        assertNull(echoOptionalI32(null))
        demoCase("case:options.primitives.f64.should_roundtrip_some")
        assertDoubleEquals(4.5, echoOptionalF64(4.5)!!)
        demoCase("case:options.primitives.f64.should_roundtrip_none")
        assertNull(echoOptionalF64(null))
        demoCase("case:options.primitives.bool.should_roundtrip_some")
        assertEquals(true, echoOptionalBool(true))
        demoCase("case:options.primitives.bool.should_roundtrip_none")
        assertNull(echoOptionalBool(null))
        demoCase("case:options.primitives.i32.should_unwrap_some")
        assertEquals(9, unwrapOrDefaultI32(9, 4))
        demoCase("case:options.primitives.i32.should_use_default_for_none")
        assertEquals(4, unwrapOrDefaultI32(null, 4))
        demoCase("case:options.primitives.i32.should_make_some")
        assertEquals(12, makeSomeI32(12))
        demoCase("case:options.primitives.i32.should_make_none")
        assertNull(makeNoneI32())
        demoCase("case:options.primitives.i32.should_double_some")
        assertEquals(16, doubleIfSome(8))
        demoCase("case:options.primitives.i32.should_preserve_none_when_doubling")
        assertNull(doubleIfSome(null))
        demoCase("case:options.primitives.i32.should_find_even_value")
        assertEquals(8, findEven(8))
        demoCase("case:options.primitives.i32.should_return_none_for_odd_value")
        assertNull(findEven(7))
        demoCase("case:options.primitives.i64.should_find_positive_value")
        assertEquals(42L, findPositiveI64(42L))
        demoCase("case:options.primitives.i64.should_return_none_for_non_positive_value")
        assertNull(findPositiveI64(-1L))
        demoCase("case:options.primitives.f64.should_find_positive_value")
        assertDoubleEquals(3.5, findPositiveF64(3.5)!!)
        demoCase("case:options.primitives.f64.should_return_none_for_non_positive_value")
        assertNull(findPositiveF64(-0.1))

        demoCase("case:options.complex.string.should_roundtrip_some")
        assertEquals("hello", echoOptionalString("hello"))
        demoCase("case:options.complex.string.should_roundtrip_none")
        assertNull(echoOptionalString(null))
        demoCase("case:options.complex.string.should_report_some")
        assertEquals(true, isSomeString("x"))
        demoCase("case:options.complex.string.should_report_none")
        assertEquals(false, isSomeString(null))
        demoCase("case:options.complex.string.should_find_name_for_positive_id")
        assertEquals("Name_42", findName(42))
        demoCase("case:options.complex.string.should_return_none_for_non_positive_id")
        assertNull(findName(0))

        demoCase("case:options.complex.point.should_roundtrip_some")
        assertPointEquals(1.0, 2.0, echoOptionalPoint(Point(1.0, 2.0))!!)
        demoCase("case:options.complex.point.should_roundtrip_none")
        assertNull(echoOptionalPoint(null))
        demoCase("case:options.complex.point.should_make_some")
        assertPointEquals(3.0, 4.0, makeSomePoint(3.0, 4.0)!!)
        demoCase("case:options.complex.point.should_make_none")
        assertNull(makeNonePoint())

        demoCase("case:options.complex.status.should_roundtrip_some")
        assertEquals(Status.ACTIVE, echoOptionalStatus(Status.ACTIVE))
        demoCase("case:options.complex.status.should_roundtrip_none")
        assertNull(echoOptionalStatus(null))
        demoCase("case:options.complex.vec.should_roundtrip_some")
        assertContentEquals(intArrayOf(1, 2, 3), echoOptionalVec(intArrayOf(1, 2, 3)))
        demoCase("case:options.complex.vec.should_roundtrip_none")
        assertNull(echoOptionalVec(null))
        demoCase("case:options.complex.vec.should_report_length_for_some")
        assertEquals(2u, optionalVecLength(intArrayOf(9, 8)))
        demoCase("case:options.complex.vec.should_return_none_for_absent_length")
        assertNull(optionalVecLength(null))
        demoCase("case:options.complex.vec.should_roundtrip_empty_some")
        assertContentEquals(intArrayOf(), echoOptionalVec(intArrayOf()))
        demoCase("case:options.complex.vec.should_find_numbers_for_positive_count")
        assertContentEquals(intArrayOf(0, 1, 2), findNumbers(3))
        demoCase("case:options.complex.vec.should_return_none_for_non_positive_number_count")
        assertNull(findNumbers(-1))
        demoCase("case:options.complex.vec_string.should_find_names_for_positive_count")
        assertEquals(listOf("Name_0", "Name_1"), findNames(2))
        demoCase("case:options.complex.vec_string.should_return_none_for_non_positive_name_count")
        assertNull(findNames(0))
        demoCase("case:options.complex.api_result.should_find_success_variant")
        assertEquals(ApiResult.Success, findApiResult(0))
        demoCase("case:options.complex.api_result.should_find_error_code_variant")
        assertEquals(ApiResult.ErrorCode(-1), findApiResult(1))
        demoCase("case:options.complex.api_result.should_find_error_with_data_variant")
        assertEquals(ApiResult.ErrorWithData(-1, -2), findApiResult(2))
        demoCase("case:options.complex.api_result.should_return_none_for_unknown_code")
        assertNull(findApiResult(99))

        // Vec<Option<T>>: each element carries its own present/absent tag.
        // Mixed positions surface any off-by-one errors in the per-slot
        // Option encoding inside the encoded-array wire path.
        demoCase("case:options.complex.vec_optional_i32.should_roundtrip_mixed_presence")
        val mixedOptionals = listOf(1, null, 3, null, 5)
        assertEquals(mixedOptionals, echoVecOptionalI32(mixedOptionals))
        demoCase("case:options.complex.vec_optional_i32.should_roundtrip_empty")
        assertEquals(emptyList(), echoVecOptionalI32(emptyList()))
        demoCase("case:options.complex.vec_optional_i32.should_roundtrip_all_none")
        assertEquals(listOf(null, null, null), echoVecOptionalI32(listOf(null, null, null)))

        demoCase("case:options.complex.shape.should_return_radius_for_circle")
        assertDoubleEquals(5.0, radiusIfCircle(Shape.Circle(5.0))!!)
        demoCase("case:options.complex.shape.should_return_none_for_non_circle")
        assertNull(radiusIfCircle(Shape.Rectangle(3.0, 4.0)))
    }

    @Test
    fun basicStringResultFunctionsUseCorrectKotlinSurface() {
        demoCase("case:results.basic.safe_divide.should_return_quotient")
        assertEquals(5, safeDivide(10, 2))
        demoCase("case:results.basic.safe_divide.should_reject_division_by_zero")
        assertMessageContains(assertFailsWith<FfiException> { safeDivide(1, 0) }, "division by zero")
        demoCase("case:results.basic.divide.should_return_quotient")
        assertEquals(4, divide(20, 5))
        demoCase("case:results.basic.divide.should_reject_division_by_zero")
        assertMessageContains(assertFailsWith<FfiException> { divide(1, 0) }, "division by zero")
        demoCase("case:results.basic.parse_int.should_parse_integer")
        assertEquals(42, parseInt("42"))
        demoCase("case:results.basic.parse_int.should_reject_invalid_integer")
        assertMessageContains(assertFailsWith<FfiException> { parseInt("not-a-number") }, "invalid integer")
        demoCase("case:results.basic.is_even.should_return_parity")
        assertEquals(true, isEven(4))
        assertEquals(false, isEven(3))
        demoCase("case:results.basic.is_even.should_reject_negative_input")
        assertMessageContains(assertFailsWith<FfiException> { isEven(-1) }, "negative input")
        demoCase("case:results.basic.validate_name.should_greet_valid_name")
        assertEquals("Hello, Ada!", validateName("Ada"))
        demoCase("case:results.basic.validate_name.should_reject_empty_name")
        assertMessageContains(assertFailsWith<FfiException> { validateName("") }, "name cannot be empty")
        demoCase("case:results.basic.safe_sqrt.should_return_square_root")
        assertDoubleEquals(3.0, safeSqrt(9.0))
        demoCase("case:results.basic.safe_sqrt.should_reject_negative_input")
        assertMessageContains(assertFailsWith<FfiException> { safeSqrt(-1.0) }, "negative input")
        demoCase("case:results.basic.parse_point.should_parse_coordinates")
        assertPointEquals(1.5, 2.5, parsePoint("1.5, 2.5"))
        demoCase("case:results.basic.parse_point.should_reject_malformed_input")
        assertMessageContains(assertFailsWith<FfiException> { parsePoint("wat") }, "expected format")
        demoCase("case:results.basic.always_ok.should_return_doubled_value")
        assertEquals(42, alwaysOk(21))
        demoCase("case:results.basic.always_err.should_return_message_error")
        assertMessageContains(assertFailsWith<FfiException> { alwaysErr("boom") }, "boom")
        demoCase("case:results.basic.result_to_string.should_render_ok")
        assertEquals("ok: 7", resultToString(BoltFFIResult.Ok(7)))
        demoCase("case:results.basic.result_to_string.should_render_err")
        assertEquals("err: bad", resultToString(BoltFFIResult.Err("bad")))
    }

    @Test
    fun typedErrorResultFunctionsUseCorrectKotlinSurface() {
        demoCase("case:results.error_enums.checked_divide.should_return_quotient")
        assertEquals(5, checkedDivide(10, 2))
        demoCase("case:results.error_enums.checked_divide.should_reject_division_by_zero")
        assertTrue(assertFailsWith<MathError> { checkedDivide(1, 0) } is MathError.DivisionByZero)
        demoCase("case:results.error_enums.checked_sqrt.should_return_square_root")
        assertDoubleEquals(3.0, checkedSqrt(9.0))
        demoCase("case:results.error_enums.checked_sqrt.should_reject_negative_input")
        assertTrue(assertFailsWith<MathError> { checkedSqrt(-1.0) } is MathError.NegativeInput)
        demoCase("case:results.error_enums.checked_add.should_return_sum")
        assertEquals(7, checkedAdd(3, 4))
        demoCase("case:results.error_enums.checked_add.should_reject_overflow")
        assertTrue(assertFailsWith<MathError> { checkedAdd(Int.MAX_VALUE, 1) } is MathError.Overflow)

        demoCase("case:results.error_enums.may_fail.should_return_success_when_valid")
        assertEquals("Success!", mayFail(true))
        demoCase("case:results.error_enums.may_fail.should_return_app_error_when_invalid")
        val invalidInputError = assertFailsWith<AppError> { mayFail(false) }
        assertEquals(400, invalidInputError.code)
        assertEquals("Invalid input", invalidInputError.message)

        demoCase("case:results.error_enums.divide_app.should_return_quotient")
        assertEquals(5, divideApp(10, 2))
        demoCase("case:results.error_enums.divide_app.should_return_app_error_for_division_by_zero")
        val divideByZeroError = assertFailsWith<AppError> { divideApp(10, 0) }
        assertEquals(500, divideByZeroError.code)
        assertEquals("Division by zero", divideByZeroError.message)

        demoCase("case:results.error_enums.validate_username.should_accept_valid_name")
        assertEquals("valid_name", validateUsername("valid_name"))
        demoCase("case:results.error_enums.validate_username.should_reject_too_short_name")
        assertTrue(assertFailsWith<ValidationError> { validateUsername("ab") } is ValidationError.TooShort)
        demoCase("case:results.error_enums.validate_username.should_reject_too_long_name")
        assertTrue(
            assertFailsWith<ValidationError> { validateUsername("a".repeat(21)) } is ValidationError.TooLong
        )
        demoCase("case:results.error_enums.validate_username.should_reject_invalid_format")
        assertTrue(
            assertFailsWith<ValidationError> { validateUsername("has space") } is ValidationError.InvalidFormat
        )

        demoCase("case:results.error_enums.process_value.should_return_success_variant")
        assertEquals(ApiResult.Success, processValue(5))
        demoCase("case:results.error_enums.process_value.should_return_error_code_variant")
        assertEquals(ApiResult.ErrorCode(-1), processValue(0))
        demoCase("case:results.error_enums.process_value.should_return_error_with_data_variant")
        assertEquals(ApiResult.ErrorWithData(-3, -6), processValue(-3))
        demoCase("case:results.error_enums.api_result_is_success.should_report_success_variant")
        assertTrue(apiResultIsSuccess(ApiResult.Success))
        demoCase("case:results.error_enums.api_result_is_success.should_report_error_variant")
        assertEquals(false, apiResultIsSuccess(ApiResult.ErrorCode(-1)))
        demoCase("case:results.error_enums.try_compute.should_return_doubled_value")
        assertEquals(20, tryCompute(10))
        demoCase("case:results.error_enums.try_compute.should_return_overflow_error")
        assertIs<ComputeError.Overflow>(assertFailsWith<ComputeError> { tryCompute(-2) })

        val benchmarkPoint = DataPoint(1.5, 2.5, 1_700_000_000_000L)
        demoCase("case:results.error_enums.benchmark_response.should_make_success_response")
        val benchmarkSuccess = createSuccessResponse(42L, benchmarkPoint)
        assertEquals(42L, benchmarkSuccess.requestId)
        assertEquals(BoltFFIResult.Ok(benchmarkPoint), benchmarkSuccess.result)
        demoCase("case:results.error_enums.benchmark_response.should_make_error_response")
        val benchmarkError = createErrorResponse(7L, ComputeError.InvalidInput(-9))
        assertEquals(7L, benchmarkError.requestId)
        assertTrue(benchmarkError.result is BoltFFIResult.Err)
        demoCase("case:results.error_enums.benchmark_response.should_report_success_response")
        assertTrue(isResponseSuccess(benchmarkSuccess))
        demoCase("case:results.error_enums.benchmark_response.should_report_error_response")
        assertEquals(false, isResponseSuccess(benchmarkError))
        demoCase("case:results.error_enums.benchmark_response.should_return_value_for_success_response")
        assertEquals(benchmarkPoint, getResponseValue(benchmarkSuccess))
        demoCase("case:results.error_enums.benchmark_response.should_return_none_for_error_response")
        assertNull(getResponseValue(benchmarkError))
    }

    @Test
    fun nestedResultFunctionsUseCorrectKotlinSurface() {
        demoCase("case:results.nested_results.option.should_return_some_for_positive_key")
        assertEquals(8, resultOfOption(4))
        demoCase("case:results.nested_results.option.should_return_none_for_zero_key")
        assertNull(resultOfOption(0))
        demoCase("case:results.nested_results.option.should_reject_negative_key")
        assertMessageContains(assertFailsWith<FfiException> { resultOfOption(-1) }, "invalid key")
        demoCase("case:results.nested_results.vec.should_return_values_for_non_negative_count")
        assertContentEquals(intArrayOf(0, 1, 2), resultOfVec(3))
        demoCase("case:results.nested_results.vec.should_reject_negative_count")
        assertMessageContains(assertFailsWith<FfiException> { resultOfVec(-1) }, "negative count")
        demoCase("case:results.nested_results.string.should_return_value_for_non_negative_key")
        assertEquals("item_7", resultOfString(7))
        demoCase("case:results.nested_results.string.should_reject_negative_key")
        assertMessageContains(assertFailsWith<FfiException> { resultOfString(-1) }, "invalid key")
    }

    @Test
    fun enumAndDataEnumExportsBehaveCorrectly() {
        demoCase("case:enums.c_style.status.should_roundtrip_values")
        assertEquals(Status.ACTIVE, echoStatus(Status.ACTIVE))
        demoCase("case:enums.c_style.status.should_render_labels")
        assertEquals("active", statusToString(Status.ACTIVE))
        demoCase("case:enums.c_style.status.should_identify_active_values")
        assertEquals(false, isActive(Status.PENDING))

        demoCase("case:enums.c_style.status.should_roundtrip_vectors")
        assertEquals(listOf(Status.ACTIVE, Status.PENDING), echoVecStatus(listOf(Status.ACTIVE, Status.PENDING)))

        demoCase("case:enums.c_style.direction.should_construct_from_raw_value")
        assertEquals(Direction.WEST, Direction.new(3))
        demoCase("case:enums.c_style.direction.should_return_cardinal_value")
        assertEquals(Direction.NORTH, Direction.cardinal())
        demoCase("case:enums.c_style.direction.should_construct_from_degrees")
        assertEquals(Direction.EAST, Direction.fromDegrees(90.0))
        demoCase("case:enums.c_style.direction.should_report_variant_count")
        assertEquals(4u, Direction.count())
        demoCase("case:enums.c_style.direction.should_return_opposite_from_method")
        assertEquals(Direction.SOUTH, Direction.NORTH.opposite())
        demoCase("case:enums.c_style.direction.should_return_method_parameter_value")
        assertEquals(Direction.WEST, Direction.NORTH.horizontalOr(Direction.WEST))
        assertEquals(Direction.EAST, Direction.EAST.horizontalOr(Direction.WEST))
        demoCase("case:enums.c_style.direction.should_identify_horizontal_values")
        assertEquals(true, Direction.EAST.isHorizontal())
        demoCase("case:enums.c_style.direction.should_render_compass_label")
        assertEquals("W", Direction.WEST.label())
        demoCase("case:enums.c_style.direction.should_roundtrip_value")
        assertEquals(Direction.EAST, echoDirection(Direction.EAST))
        demoCase("case:enums.c_style.direction.should_return_opposite_from_free_function")
        assertEquals(Direction.WEST, oppositeDirection(Direction.EAST))
        demoCase("case:enums.c_style.direction.should_return_degrees")
        assertEquals(0, directionToDegrees(Direction.NORTH))
        assertEquals(90, directionToDegrees(Direction.EAST))
        assertEquals(180, directionToDegrees(Direction.SOUTH))
        assertEquals(270, directionToDegrees(Direction.WEST))

        val directionSequence = generateDirections(5)
        demoCase("case:enums.c_style.direction.should_generate_sequence")
        assertEquals(
            listOf(Direction.NORTH, Direction.EAST, Direction.SOUTH, Direction.WEST, Direction.NORTH),
            directionSequence
        )
        demoCase("case:enums.c_style.direction.should_count_north_values")
        assertEquals(2, countNorth(directionSequence))
        demoCase("case:enums.c_style.direction.find_direction.should_return_some_for_known_id")
        assertEquals(Direction.SOUTH, findDirection(2))
        demoCase("case:enums.c_style.direction.find_direction.should_return_none_for_unknown_id")
        assertNull(findDirection(99))
        demoCase("case:enums.c_style.direction.find_directions.should_return_sequence_for_positive_count")
        assertEquals(listOf(Direction.NORTH, Direction.EAST, Direction.SOUTH), findDirections(3))
        demoCase("case:enums.c_style.direction.find_directions.should_return_none_for_non_positive_count")
        assertNull(findDirections(0))

        val nameFilter = Filter.ByName("ali")
        val pointFilter = Filter.ByPoints(listOf(Point(0.0, 0.0), Point(1.0, 1.0)))
        val groupFilter = Filter.ByGroups(listOf(listOf("café", "🌍"), emptyList(), listOf("common")))
        demoCase("case:enums.complex_variants.filter.none.should_roundtrip_unit_variant")
        assertEquals(Filter.None, echoFilter(Filter.None))
        demoCase("case:enums.complex_variants.filter.by_name.should_roundtrip_string_payload")
        assertEquals(nameFilter, echoFilter(nameFilter))
        demoCase("case:enums.complex_variants.filter.by_groups.should_roundtrip_nested_string_vectors")
        assertEquals(groupFilter, echoFilter(groupFilter))
        demoCase("case:enums.complex_variants.filter.by_points.should_roundtrip_record_vector_payload")
        assertEquals(pointFilter, echoFilter(pointFilter))
        val tagFilter = Filter.ByTags(listOf("ffi", "jni", "kmp"))
        demoCase("case:enums.complex_variants.filter.by_tags.should_roundtrip_string_vector_payload")
        assertEquals(tagFilter, echoFilter(tagFilter))
        demoCase("case:enums.complex_variants.filter.by_name.should_describe_string_payload")
        assertEquals("filter by name: ali", describeFilter(nameFilter))
        demoCase("case:enums.complex_variants.filter.by_points.should_describe_record_vector_payload")
        assertEquals("filter by 2 anchor points", describeFilter(pointFilter))
        demoCase("case:enums.complex_variants.filter.by_tags.should_describe_string_vector_payload")
        assertEquals("filter by 2 tags", describeFilter(Filter.ByTags(listOf("ffi", "jni"))))
        demoCase("case:enums.complex_variants.filter.by_groups.should_describe_nested_string_vectors")
        assertEquals("filter by 3 groups", describeFilter(groupFilter))
        demoCase("case:enums.complex_variants.filter.by_range.should_describe_numeric_bounds")
        assertEquals("filter by range: 1..5", describeFilter(Filter.ByRange(1.0, 5.0)))

        val success = ApiResponse.Success("ok")
        val redirect = ApiResponse.Redirect("https://example.com")
        demoCase("case:enums.complex_variants.api_response.success.should_roundtrip_string_payload")
        assertEquals(success, echoApiResponse(success))
        demoCase("case:enums.complex_variants.api_response.redirect.should_roundtrip_url_payload")
        assertEquals(redirect, echoApiResponse(redirect))
        demoCase("case:enums.complex_variants.api_response.success.should_identify_success")
        assertEquals(true, isSuccess(success))
        demoCase("case:enums.complex_variants.api_response.empty.should_not_identify_as_success")
        assertEquals(false, isSuccess(ApiResponse.Empty))

        demoCase("case:enums.repr_int.priority.should_roundtrip_value")
        assertEquals(Priority.HIGH, echoPriority(Priority.HIGH))
        demoCase("case:enums.repr_int.priority.should_render_label")
        assertEquals("low", priorityLabel(Priority.LOW))
        demoCase("case:enums.repr_int.priority.should_identify_high_priority")
        assertEquals(true, isHighPriority(Priority.CRITICAL))
        assertEquals(false, isHighPriority(Priority.LOW))
        demoCase("case:enums.repr_int.log_level.should_roundtrip_value")
        assertEquals(LogLevel.INFO, echoLogLevel(LogLevel.INFO))
        demoCase("case:enums.repr_int.log_level.should_compare_against_minimum")
        assertEquals(true, shouldLog(LogLevel.ERROR, LogLevel.WARN))

        demoCase("case:enums.repr_int.log_level.should_roundtrip_vectors")
        assertEquals(
            listOf(LogLevel.TRACE, LogLevel.INFO, LogLevel.ERROR),
            echoVecLogLevel(listOf(LogLevel.TRACE, LogLevel.INFO, LogLevel.ERROR))
        )

        demoCase("case:enums.repr_int.http_code.should_expose_discriminant_values")
        assertEquals(200.toShort(), HttpCode.OK.value)
        assertEquals(404.toShort(), HttpCode.NOT_FOUND.value)
        assertEquals(500.toShort(), HttpCode.SERVER_ERROR.value)
        demoCase("case:enums.repr_int.http_code.should_return_not_found")
        assertEquals(HttpCode.NOT_FOUND, httpCodeNotFound())
        demoCase("case:enums.repr_int.http_code.should_roundtrip_values")
        assertEquals(HttpCode.OK, echoHttpCode(HttpCode.OK))
        assertEquals(HttpCode.SERVER_ERROR, echoHttpCode(HttpCode.SERVER_ERROR))

        demoCase("case:enums.repr_int.sign.should_expose_signed_discriminant_values")
        assertEquals((-1).toByte(), Sign.NEGATIVE.value)
        assertEquals(0.toByte(), Sign.ZERO.value)
        assertEquals(1.toByte(), Sign.POSITIVE.value)
        demoCase("case:enums.repr_int.sign.should_return_negative")
        assertEquals(Sign.NEGATIVE, signNegative())
        demoCase("case:enums.repr_int.sign.should_roundtrip_signed_values")
        assertEquals(Sign.NEGATIVE, echoSign(Sign.NEGATIVE))
        assertEquals(Sign.POSITIVE, echoSign(Sign.POSITIVE))

        demoCase("case:enums.data_enum.shape.should_support_primary_constructor")
        val circle = Shape.new(5.0)
        assertIs<Shape.Circle>(circle)

        demoCase("case:enums.data_enum.shape.unit_circle.should_construct_circle")
        assertIs<Shape.Circle>(Shape.unitCircle())
        demoCase("case:enums.data_enum.shape.square.should_construct_rectangle")
        assertIs<Shape.Rectangle>(Shape.square(3.0))
        demoCase("case:enums.data_enum.shape.try_circle.should_return_circle_for_positive_radius")
        assertIs<Shape.Circle>(Shape.tryCircle(2.0))
        demoCase("case:enums.data_enum.shape.maybe_circle.should_return_some_for_positive_radius")
        assertIs<Shape.Circle>(Shape.maybeCircle(2.0))
        demoCase("case:enums.data_enum.shape.maybe_circle.should_return_none_for_non_positive_radius")
        assertNull(Shape.maybeCircle(-1.0))

        demoCase("case:enums.data_enum.shape.should_reject_non_positive_circle_radius")
        assertMessageContains(assertFailsWith<FfiException> { Shape.tryCircle(-1.0) }, "radius must be positive")

        demoCase("case:enums.data_enum.shape.should_report_variant_count")
        assertEquals(6u, Shape.variantCount())

        demoCase("case:enums.data_enum.shape.should_support_numeric_instance_methods")
        assertDoubleEquals(PI * 25.0, circle.area(), 1e-6)

        demoCase("case:enums.data_enum.shape.should_support_string_instance_methods")
        assertEquals("circle r=5", circle.describe())

        demoCase("case:enums.data_enum.shape.should_support_free_function_factories")
        assertIs<Shape.Circle>(makeCircle(2.0))
        assertIs<Shape.Rectangle>(makeRectangle(3.0, 4.0))

        demoCase("case:enums.data_enum.shape.should_roundtrip_core_variants")
        assertIs<Shape.Circle>(echoShape(Shape.Circle(2.0)))
        assertIs<Shape.Rectangle>(echoShape(Shape.Rectangle(3.0, 4.0)))
        assertIs<Shape.Triangle>(echoShape(Shape.Triangle(Point(0.0, 0.0), Point(3.0, 0.0), Point(0.0, 4.0))))
        assertEquals(Shape.Point, echoShape(Shape.Point))

        demoCase("case:enums.data_enum.shape.apex.should_roundtrip_some_point_payload")
        assertEquals(Shape.Apex(Point(3.0, 4.0)), echoShape(Shape.Apex(Point(3.0, 4.0))))
        demoCase("case:enums.data_enum.shape.apex.should_roundtrip_none_payload")
        assertEquals(Shape.Apex(null), echoShape(Shape.Apex(null)))

        demoCase("case:enums.data_enum.shape.should_roundtrip_vector_record_fields")
        assertEquals(Shape.Cluster(listOf(Point(1.0, 2.0))), echoShape(Shape.Cluster(listOf(Point(1.0, 2.0)))))

        demoCase("case:enums.data_enum.shape.try_apex_point.should_return_some_for_positive_radius")
        assertEquals(Point(0.0, 2.5), Shape.tryApexPoint(2.5))
        demoCase("case:enums.data_enum.shape.try_apex_point.should_return_none_for_non_positive_radius")
        assertNull(Shape.tryApexPoint(-1.0))

        demoCase("case:enums.data_enum.shape.should_roundtrip_vectors")
        assertEquals(3, echoVecShape(listOf(Shape.Circle(2.0), Shape.Rectangle(3.0, 4.0), Shape.Point)).size)

        demoCase("case:enums.data_enum.message.text.should_roundtrip_string_payload")
        assertEquals(Message.Text("hello"), echoMessage(Message.Text("hello")))
        demoCase("case:enums.data_enum.message.image.should_roundtrip_url_dimensions_payload")
        assertEquals(
            Message.Image("https://example.com/image.png", 640u, 480u),
            echoMessage(Message.Image("https://example.com/image.png", 640u, 480u))
        )
        demoCase("case:enums.data_enum.message.ping.should_roundtrip_unit_variant")
        assertEquals(Message.Ping, echoMessage(Message.Ping))
        demoCase("case:enums.data_enum.message.text.should_render_text_summary")
        assertEquals("text: hi", messageSummary(Message.Text("hi")))
        demoCase("case:enums.data_enum.message.image.should_render_image_summary")
        assertEquals(
            "image: 640x480 at https://example.com/image.png",
            messageSummary(Message.Image("https://example.com/image.png", 640u, 480u))
        )
        demoCase("case:enums.data_enum.message.ping.should_render_ping_summary")
        assertEquals("ping", messageSummary(Message.Ping))

        demoCase("case:enums.data_enum.animal.dog.should_roundtrip_string_payloads")
        assertEquals(Animal.Dog("Rex", "Labrador"), echoAnimal(Animal.Dog("Rex", "Labrador")))
        demoCase("case:enums.data_enum.animal.cat.should_roundtrip_name_and_bool_payload")
        assertEquals(Animal.Cat("Milo", true), echoAnimal(Animal.Cat("Milo", true)))
        demoCase("case:enums.data_enum.animal.fish.should_roundtrip_count_payload")
        assertEquals(Animal.Fish(7u), echoAnimal(Animal.Fish(7u)))
        demoCase("case:enums.data_enum.animal.fish.should_derive_count_label")
        assertEquals("5 fish", animalName(Animal.Fish(5u)))
        demoCase("case:enums.data_enum.animal.cat.should_derive_name")
        assertEquals("Milo", animalName(Animal.Cat("Milo", true)))
        demoCase("case:enums.data_enum.animal.dog.should_derive_name")
        assertEquals("Rex", animalName(Animal.Dog("Rex", "Labrador")))
    }

    @Test
    fun pointAndRecordMethodExportsBehaveCorrectly() {
        demoCase("case:records.blittable.point.should_construct_with_static_new")
        assertEquals(Point(1.0, 2.0), Point.new(1.0, 2.0))
        demoCase("case:records.blittable.point.should_return_origin")
        assertPointEquals(0.0, 0.0, Point.origin())
        demoCase("case:records.blittable.point.should_construct_from_polar_coordinates")
        assertPointEquals(0.0, 2.0, Point.fromPolar(2.0, PI / 2.0), 1e-6)
        demoCase("case:records.blittable.point.should_normalize_unit_vector")
        assertPointEquals(0.6, 0.8, Point.tryUnit(3.0, 4.0), 1e-6)
        demoCase("case:records.blittable.point.should_reject_zero_unit_vector")
        assertMessageContains(assertFailsWith<FfiException> { Point.tryUnit(0.0, 0.0) }, "cannot normalize zero vector")
        demoCase("case:records.blittable.point.should_return_some_for_checked_unit")
        assertPointEquals(1.0, 0.0, Point.checkedUnit(2.0, 0.0)!!, 1e-6)
        demoCase("case:records.blittable.point.should_return_none_for_zero_checked_unit")
        assertNull(Point.checkedUnit(0.0, 0.0))
        demoCase("case:records.blittable.point.should_report_dimension_count")
        assertEquals(2u, Point.dimensions())
        demoCase("case:records.blittable.point.should_compute_distance")
        assertDoubleEquals(5.0, Point(3.0, 4.0).distance())
        demoCase("case:records.blittable.point.should_scale_coordinates")
        assertPointEquals(6.0, 8.0, Point(3.0, 4.0).scale(2.0))
        demoCase("case:records.blittable.point.should_add_coordinates")
        assertPointEquals(4.0, 6.0, Point(1.0, 2.0).add(Point(3.0, 4.0)))
        demoCase("case:records.blittable.point.should_compute_path_length")
        assertDoubleEquals(
            10.0,
            Point.pathLength(listOf(Point(0.0, 0.0), Point(3.0, 4.0), Point(6.0, 8.0)))
        )
        demoCase("case:records.blittable.point.should_roundtrip_value")
        assertEquals(Point(1.0, 2.0), echoPoint(Point(1.0, 2.0)))
        demoCase("case:records.blittable.point.should_make_from_coordinates")
        assertEquals(Point(1.0, 2.0), makePoint(1.0, 2.0))
        demoCase("case:records.blittable.point.should_add_values")
        assertEquals(Point(8.0, 10.0), addPoints(Point(3.0, 4.0), Point(5.0, 6.0)))

        demoCase("case:records.blittable.point.should_return_some_for_nonzero_coordinates")
        assertEquals(Point(2.0, 3.0), tryMakePoint(2.0, 3.0))
        demoCase("case:records.blittable.point.should_return_none_for_origin_coordinates")
        assertNull(tryMakePoint(0.0, 0.0))

        val color = Color(1u, 2u, 3u, 255u)
        demoCase("case:records.blittable.color.should_roundtrip_value")
        assertEquals(color, echoColor(color))
        demoCase("case:records.blittable.color.should_make_from_channels")
        assertEquals(Color(9u, 8u, 7u, 6u), makeColor(9u, 8u, 7u, 6u))

        demoCase("case:records.nested.line.should_make_from_coordinates")
        val line = makeLine(0.0, 0.0, 3.0, 4.0)
        demoCase("case:records.nested.line.should_roundtrip_nested_points")
        assertEquals(line, echoLine(line))
        demoCase("case:records.nested.line.should_compute_length")
        assertDoubleEquals(5.0, lineLength(line))

        val rect = Rect(Point(1.0, 2.0), Dimensions(3.0, 4.0))
        demoCase("case:records.nested.rect.should_roundtrip_nested_records")
        assertEquals(rect, echoRect(rect))
        demoCase("case:records.nested.rect.should_compute_area")
        assertDoubleEquals(12.0, rectArea(rect))
    }

    @Test
    fun collectionAndNestedRecordExportsBehaveCorrectly() {
        demoCase("case:records.with_collections.polygon.should_make_from_points")
        val polygon = makePolygon(listOf(Point(0.0, 0.0), Point(1.0, 0.0), Point(0.0, 1.0)))
        demoCase("case:records.with_collections.polygon.should_roundtrip_point_vector")
        assertEquals(polygon, echoPolygon(polygon))
        demoCase("case:records.with_collections.polygon.should_report_vertex_count")
        assertEquals(3u, polygonVertexCount(polygon))
        demoCase("case:records.with_collections.polygon.should_compute_centroid")
        assertPointEquals(1.0 / 3.0, 1.0 / 3.0, polygonCentroid(polygon), 1e-6)

        demoCase("case:records.with_collections.team.should_make_from_members")
        val team = makeTeam("devs", listOf("Ali", "Mia"))
        demoCase("case:records.with_collections.team.should_roundtrip_member_vector")
        assertEquals(team, echoTeam(team))
        demoCase("case:records.with_collections.team.should_report_member_count")
        assertEquals(2u, teamSize(team))

        demoCase("case:records.with_collections.classroom.should_make_from_students")
        val classroom = makeClassroom(listOf(Person("Mia", 10u), Person("Leo", 11u)))
        demoCase("case:records.with_collections.classroom.should_roundtrip_student_vector")
        assertEquals(classroom, echoClassroom(classroom))

        demoCase("case:records.with_collections.tagged_scores.should_roundtrip_score_vector")
        val taggedScores = TaggedScores("math", doubleArrayOf(90.0, 85.5))
        val echoedTaggedScores = echoTaggedScores(taggedScores)
        assertEquals("math", echoedTaggedScores.label)
        assertContentEquals(doubleArrayOf(90.0, 85.5), echoedTaggedScores.scores)
        demoCase("case:records.with_collections.tagged_scores.should_average_scores")
        assertDoubleEquals(90.0, averageScore(TaggedScores("x", doubleArrayOf(80.0, 100.0))))

        val benchmarkProfiles = generateUserProfiles(4)
        demoCase("case:records.with_collections.user_profiles.should_generate_profiles")
        assertEquals(4, benchmarkProfiles.size)
        assertEquals("User 0", benchmarkProfiles[0].name)
        demoCase("case:records.with_collections.user_profiles.should_sum_scores")
        assertDoubleEquals(9.0, sumUserScores(benchmarkProfiles))
        demoCase("case:records.with_collections.user_profiles.should_count_active_users")
        assertEquals(2, countActiveUsers(benchmarkProfiles))

        demoCase("case:records.with_enums.task.should_make_incomplete_task")
        val task = makeTask("ship bindings", Priority.CRITICAL)
        assertEquals(false, task.completed)
        demoCase("case:records.with_enums.task.should_detect_urgent_priority")
        assertEquals(true, isUrgent(task))

        demoCase("case:records.with_enums.task.should_roundtrip_priority_field")
        assertEquals(task, echoTask(task))

        demoCase("case:records.with_enums.notification.should_roundtrip_priority_field")
        val notification = Notification("heads up", Priority.HIGH, false)
        assertEquals(notification, echoNotification(notification))

        demoCase("case:records.with_enums.holder.should_make_triangle_variant")
        val triangleHolder = makeTriangleHolder()
        assertIs<Shape.Triangle>(triangleHolder.shape)
        demoCase("case:records.with_enums.holder.should_roundtrip_data_enum_field")
        assertEquals(triangleHolder, echoHolder(triangleHolder))

        demoCase("case:records.with_enums.task_header.should_make_critical_header")
        val header = makeCriticalTaskHeader(42L)
        assertEquals(42L, header.id)
        assertEquals(Priority.CRITICAL, header.priority)
        assertEquals(false, header.completed)
        demoCase("case:records.with_enums.task_header.should_roundtrip_repr_enum_field")
        assertEquals(header, echoTaskHeader(header))

        demoCase("case:enums.data_enum.lifecycle_event.should_make_critical_event")
        val started = makeCriticalLifecycleEvent(7L)
        assertIs<LifecycleEvent.TaskStarted>(started)
        assertEquals(Priority.CRITICAL, started.priority)
        assertEquals(7L, started.id)
        demoCase("case:enums.data_enum.lifecycle_event.should_roundtrip_priority_payload")
        assertEquals(started, echoLifecycleEvent(started))
        demoCase("case:enums.data_enum.lifecycle_event.should_roundtrip_tick_variant")
        assertEquals(LifecycleEvent.Tick, echoLifecycleEvent(LifecycleEvent.Tick))

        demoCase("case:records.with_enums.log_entry.should_make_error_entry")
        val logEntry = makeErrorLogEntry(1234567890L, 42.toUShort())
        assertEquals(1234567890L, logEntry.timestamp)
        assertEquals(LogLevel.ERROR, logEntry.level)
        assertEquals(42.toUShort(), logEntry.code)
        demoCase("case:records.with_enums.log_entry.should_roundtrip_u8_enum_field")
        assertEquals(logEntry, echoLogEntry(logEntry))

        demoCase("case:records.with_options.user_profile.should_make_with_present_options")
        val userProfile = makeUserProfile("Alice", 30u, "alice@example.com", 98.5)
        demoCase("case:records.with_options.user_profile.should_roundtrip_present_options")
        assertEquals(userProfile, echoUserProfile(userProfile))
        demoCase("case:records.with_options.user_profile.should_display_email_when_present")
        assertEquals("Alice <alice@example.com>", userDisplayName(userProfile))
        demoCase("case:records.with_options.user_profile.should_make_with_absent_options")
        val userWithoutEmail = makeUserProfile("Bob", 22u, null, null)
        demoCase("case:records.with_options.user_profile.should_display_name_when_email_absent")
        assertEquals("Bob", userDisplayName(userWithoutEmail))
        demoCase("case:records.with_options.user_profile.should_roundtrip_absent_options")
        assertEquals(userWithoutEmail, echoUserProfile(userWithoutEmail))
        val userWithMixedOptions = UserProfile("Dax", 21u, null, 88.5)
        demoCase("case:records.with_options.user_profile.should_roundtrip_mixed_options")
        assertEquals(userWithMixedOptions, echoUserProfile(userWithMixedOptions))
        val userWithUtf8Optional = UserProfile("Élodie", 33u, "élodie@café.example", 12.5)
        demoCase("case:records.with_options.user_profile.should_roundtrip_utf8_optional_string")
        assertEquals(userWithUtf8Optional, echoUserProfile(userWithUtf8Optional))

        demoCase("case:records.with_options.search_result.should_roundtrip_present_options")
        val searchResult = SearchResult("rust ffi", 12u, "cursor-1", 0.99)
        assertEquals(searchResult, echoSearchResult(searchResult))
        demoCase("case:records.with_options.search_result.should_report_more_results_when_cursor_present")
        assertEquals(true, hasMoreResults(searchResult))
        demoCase("case:records.with_options.search_result.should_report_no_more_results_without_cursor")
        assertEquals(false, hasMoreResults(SearchResult("rust ffi", 12u, null, null)))
        val emptySearchResult = SearchResult("kotlin", 0u, null, null)
        demoCase("case:records.with_options.search_result.should_roundtrip_absent_options")
        assertEquals(emptySearchResult, echoSearchResult(emptySearchResult))

        demoCase("case:records.with_strings.person.should_make_from_fields")
        val person = makePerson("Ali", 30u)
        demoCase("case:records.with_strings.person.should_roundtrip_value")
        assertEquals(person, echoPerson(person))
        demoCase("case:records.with_strings.person.should_format_greeting")
        assertEquals("Hello, Ali! You are 30 years old.", greetPerson(person))

        demoCase("case:records.with_strings.address.should_roundtrip_value")
        val address = Address("Main St", "Amsterdam", "1000AA")
        assertEquals(address, echoAddress(address))
        demoCase("case:records.with_strings.address.should_format_value")
        assertEquals("Main St, Amsterdam, 1000AA", formatAddress(address))
    }

    @Test
    fun recordDefaultValuesSurfaceCorrectly() {
        val implicitDefaults = ServiceConfig("worker")
        assertEquals("worker", implicitDefaults.name)
        assertEquals(3, implicitDefaults.retries)
        assertEquals("standard", implicitDefaults.region)
        assertNull(implicitDefaults.endpoint)
        assertEquals("https://default", implicitDefaults.backupEndpoint)

        val customRetries = ServiceConfig("worker", 7)
        assertEquals("worker", customRetries.name)
        assertEquals(7, customRetries.retries)
        assertEquals("standard", customRetries.region)
        assertNull(customRetries.endpoint)
        assertEquals("https://default", customRetries.backupEndpoint)

        val explicitRegion = ServiceConfig("worker", 9, "eu-west")
        assertNull(explicitRegion.endpoint)
        assertEquals("https://default", explicitRegion.backupEndpoint)

        val explicitEndpoint = ServiceConfig("worker", 9, "eu-west", "https://edge")
        assertEquals("https://default", explicitEndpoint.backupEndpoint)

        val explicitBackupEndpoint = ServiceConfig(
            "worker",
            9,
            "eu-west",
            "https://edge",
            "https://backup"
        )
        demoCase("case:records.default_values.service_config.should_roundtrip_value")
        assertEquals(explicitBackupEndpoint, echoServiceConfig(explicitBackupEndpoint))
        demoCase("case:records.default_values.service_config.should_describe_values")
        assertEquals("worker:3:standard:none:https://default", implicitDefaults.describe())
        assertEquals("worker:7:standard:none:https://default", customRetries.describe())
        assertEquals("worker:9:eu-west:none:https://default", explicitRegion.describe())
        assertEquals("worker:9:eu-west:https://edge:https://default", explicitEndpoint.describe())
        assertEquals("worker:9:eu-west:https://edge:https://backup", explicitBackupEndpoint.describe())
        demoCase("case:records.default_values.service_config.should_describe_with_prefix")
        assertEquals("cfg:worker:9:eu-west:https://edge:https://backup", explicitBackupEndpoint.describeWithPrefix("cfg"))

        demoCase("case:records.default_values.service_config.from_owned_name.should_return_config")
        assertEquals("owned:3:standard:none:https://default", ServiceConfig.fromOwnedName("owned").describe())
        demoCase("case:records.default_values.service_config.from_borrowed_name.should_return_config")
        assertEquals("borrowed:3:standard:none:https://default", ServiceConfig.fromBorrowedName("borrowed").describe())
        demoCase("case:records.default_values.service_config.from_string_ref_name.should_return_config")
        assertEquals("stringref:3:standard:none:https://default", ServiceConfig.fromStringRefName("stringref").describe())
        demoCase("case:records.default_values.service_config.from_non_empty_name.should_return_config_for_non_empty_values")
        val validatedConfig = ServiceConfig.fromNonEmptyName("optional", "eu-west")
        assertEquals("optional", validatedConfig?.name)
        assertEquals("eu-west", validatedConfig?.region)
        demoCase("case:records.default_values.service_config.from_non_empty_name.should_return_none_for_empty_values")
        assertNull(ServiceConfig.fromNonEmptyName("", "eu-west"))
        assertNull(ServiceConfig.fromNonEmptyName("optional", ""))
        demoCase("case:records.default_values.service_config.try_with_retries.should_return_config")
        assertEquals("generated:5:standard:none:https://default", ServiceConfig.tryWithRetries(5).describe())
        demoCase("case:records.default_values.service_config.try_with_retries.should_reject_negative_retries")
        assertMessageContains(
            assertFailsWith<FfiException> { ServiceConfig.tryWithRetries(-1) },
            "retries must be non-negative",
        )
        demoCase("case:records.default_values.service_config.maybe_with_retries.should_return_some")
        assertEquals("generated:5:standard:none:https://default", ServiceConfig.maybeWithRetries(5)?.describe())
        demoCase("case:records.default_values.service_config.maybe_with_retries.should_return_none")
        assertNull(ServiceConfig.maybeWithRetries(-1))
    }
}
