import Demo
import XCTest

final class PrimitivesOptionsTests: DemoTestCase {
    func testPrimitiveOptionFns() {
        demoCase("case:options.primitives.i32.should_roundtrip_some")
        XCTAssertEqual(echoOptionalI32(v: 7), 7)
        demoCase("case:options.primitives.i32.should_roundtrip_none")
        XCTAssertNil(echoOptionalI32(v: nil))
        demoCase("case:options.primitives.f64.should_roundtrip_some")
        XCTAssertEqual(echoOptionalF64(v: 4.5), Optional(4.5))
        demoCase("case:options.primitives.f64.should_roundtrip_none")
        XCTAssertNil(echoOptionalF64(v: nil))
        demoCase("case:options.primitives.bool.should_roundtrip_some")
        XCTAssertEqual(echoOptionalBool(v: true), true)
        demoCase("case:options.primitives.bool.should_roundtrip_none")
        XCTAssertNil(echoOptionalBool(v: nil))
        demoCase("case:options.primitives.i32.should_unwrap_some")
        XCTAssertEqual(unwrapOrDefaultI32(v: 9, fallback: 4), 9)
        demoCase("case:options.primitives.i32.should_use_default_for_none")
        XCTAssertEqual(unwrapOrDefaultI32(v: nil, fallback: 4), 4)
        demoCase("case:options.primitives.i32.should_make_some")
        XCTAssertEqual(makeSomeI32(v: 12), 12)
        demoCase("case:options.primitives.i32.should_make_none")
        XCTAssertNil(makeNoneI32())
        demoCase("case:options.primitives.i32.should_double_some")
        XCTAssertEqual(doubleIfSome(v: 8), 16)
        demoCase("case:options.primitives.i32.should_preserve_none_when_doubling")
        XCTAssertNil(doubleIfSome(v: nil))
        demoCase("case:options.primitives.i32.should_find_even_value")
        XCTAssertEqual(findEven(value: 8), 8)
        demoCase("case:options.primitives.i32.should_return_none_for_odd_value")
        XCTAssertNil(findEven(value: 7))
        demoCase("case:options.primitives.i64.should_find_positive_value")
        XCTAssertEqual(findPositiveI64(value: 9), 9)
        demoCase("case:options.primitives.i64.should_return_none_for_non_positive_value")
        XCTAssertNil(findPositiveI64(value: -1))
        demoCase("case:options.primitives.f64.should_find_positive_value")
        XCTAssertEqual(findPositiveF64(value: 3.5), 3.5)
        demoCase("case:options.primitives.f64.should_return_none_for_non_positive_value")
        XCTAssertNil(findPositiveF64(value: -0.1))
    }
}
