package com.lomo.baseline

import org.gradle.api.DefaultTask
import org.gradle.api.file.Directory
import org.gradle.api.file.RegularFile
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.objectweb.asm.ClassReader
import org.objectweb.asm.ClassVisitor
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes
import java.io.InputStream
import java.util.jar.JarFile

@CacheableTask
abstract class StaticBaselineProfileTask : DefaultTask() {
    @get:Input
    abstract val projectDirPath: Property<String>

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val allJars: ListProperty<RegularFile>

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val allDirs: ListProperty<Directory>

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val rulesFile: RegularFileProperty

    @get:OutputFile
    abstract val outputProfile: RegularFileProperty

    @get:OutputFile
    abstract val reportFile: RegularFileProperty

    @get:Input
    @get:Optional
    abstract val maxTotalEntries: Property<Int>

    @TaskAction
    fun generate() {
        val resolvedRulesFile = resolveFile(rulesFile.get().asFile, mustExist = true)
        val rules = parseReportableRules(resolvedRulesFile.readText())
        require(rules.isNotEmpty()) { "Baseline rules file is empty: $resolvedRulesFile" }

        val entries = sortedMapOf<String, ProfileEntry>()
        allJars.get().forEach { jar ->
            JarFile(resolveFile(jar.asFile, mustExist = true)).use { jarFile ->
                jarFile.entries().asSequence()
                    .filter { !it.isDirectory && it.name.endsWith(".class") }
                    .forEach { entry ->
                        jarFile.getInputStream(entry).use { stream ->
                            processClass(stream, rules, entries)
                        }
                    }
            }
        }
        allDirs.get().forEach { dir ->
            resolveFile(dir.asFile, mustExist = true).walkTopDown()
                .filter { it.isFile && it.extension == "class" }
                .forEach { classFile ->
                    classFile.inputStream().use { stream ->
                        processClass(stream, rules, entries)
                    }
                }
        }

        val outputFile = resolveFile(outputProfile.get().asFile, mustExist = false)
        outputFile.parentFile.mkdirs()
        outputFile.bufferedWriter().use { writer ->
            writer.appendLine("# Generated by static baseline profile task.")
            entries.keys.forEach(writer::appendLine)
        }

        val maxEntries = maxTotalEntries.orNull
        require(maxEntries == null || maxEntries >= 0) {
            "maxTotalEntries must be non-negative when configured: $maxEntries"
        }

        val reportOutputFile = resolveFile(reportFile.get().asFile, mustExist = false)
        reportOutputFile.parentFile.mkdirs()
        reportOutputFile.writeText(
            buildReport(
                entries = entries.values.toList(),
                rules = rules,
                maxEntries = maxEntries,
            ),
        )

        if (maxEntries != null && entries.size > maxEntries) {
            throw IllegalStateException(
                "Static baseline profile entry budget exceeded: actual=${entries.size}, max=$maxEntries",
            )
        }
    }

    private fun resolveFile(
        file: java.io.File,
        mustExist: Boolean,
    ): java.io.File {
        if (file.exists() || !file.isAbsolute) {
            return file
        }

        val configuredProjectDir = java.io.File(projectDirPath.get()).absoluteFile.toPath()
        val filePath = file.absoluteFile.toPath()
        if (!filePath.startsWith(configuredProjectDir)) {
            return file
        }

        val fallback = configuredProjectDir.resolve(configuredProjectDir.relativize(filePath)).toFile()
        return if (!mustExist || fallback.exists()) fallback else file
    }

    private fun processClass(
        stream: InputStream,
        rules: List<ReportableBaselineRule>,
        entries: MutableMap<String, ProfileEntry>,
    ) {
        val collector = ClassEntryCollector()
        ClassReader(stream).accept(collector, ClassReader.SKIP_FRAMES or ClassReader.SKIP_DEBUG or ClassReader.SKIP_CODE)
        val internalName = collector.internalName ?: return
        val rule = rules.firstOrNull { it.rule.matches(internalName) } ?: return

        if (rule.classFlags.isNotEmpty()) {
            entries.putProfileEntry(
                line = "${rule.classFlags}$internalName;",
                rule = rule,
            )
        }
        collector.methods.forEach { method ->
            entries.putProfileEntry(
                line = "${rule.methodFlags}$internalName;->${method.name}${method.descriptor}",
                rule = rule,
            )
        }
    }

    private fun parseReportableRules(text: String): List<ReportableBaselineRule> {
        val normalizedRuleLines =
            text.lineSequence()
                .map { it.substringBefore('#').trim() }
                .filter { it.isNotEmpty() }
                .toList()
        val parsedRules = BaselineRule.parse(text)
        return parsedRules.zip(normalizedRuleLines).map { (rule, sourceLine) ->
            ReportableBaselineRule(
                displayName = sourceLine,
                packagePrefix = packagePrefixFor(sourceLine),
                classFlags = rule.classFlags,
                methodFlags = rule.methodFlags,
                rule = rule,
            )
        }
    }

    private fun MutableMap<String, ProfileEntry>.putProfileEntry(
        line: String,
        rule: ReportableBaselineRule,
    ) {
        putIfAbsent(
            line,
            ProfileEntry(
                rule = rule,
            ),
        )
    }

    private fun buildReport(
        entries: List<ProfileEntry>,
        rules: List<ReportableBaselineRule>,
        maxEntries: Int?,
    ): String {
        val lines = mutableListOf<String>()
        val matchedRuleNames = entries.map { it.rule.displayName }.toSet()
        lines += "# Generated by static baseline profile task."
        lines += "totalEntries=${entries.size}"
        lines += "configuredRuleGlobs=${rules.size}"
        lines += "matchedRuleGlobs=${matchedRuleNames.size}"
        lines += "maxTotalEntries=${maxEntries?.toString() ?: "unbounded"}"
        lines += "budgetStatus=${budgetStatus(entries.size, maxEntries)}"
        lines += ""
        lines += "[entriesByPackagePrefix]"
        entries.countBy { it.rule.packagePrefix }
            .forEach { (packagePrefix, count) -> lines += "$packagePrefix=$count" }
        lines += ""
        lines += "[entriesByBaselineRuleGlob]"
        entries.countBy { it.rule.displayName }
            .forEach { (ruleName, count) -> lines += "$ruleName=$count" }
        return lines.joinToString(separator = "\n", postfix = "\n")
    }

    private fun budgetStatus(
        entryCount: Int,
        maxEntries: Int?,
    ): String =
        when {
            maxEntries == null -> "PASS"
            entryCount <= maxEntries -> "PASS"
            else -> "FAIL"
        }

    private fun <T> Iterable<T>.countBy(selector: (T) -> String): Map<String, Int> =
        groupingBy(selector)
            .eachCount()
            .toSortedMap()

    private fun packagePrefixFor(ruleLine: String): String {
        val pattern = ruleLine.substringAfter(' ', missingDelimiterValue = ruleLine)
        val wildcardIndex = pattern.indexOf('*')
        val staticPrefix =
            if (wildcardIndex >= 0) {
                pattern.take(wildcardIndex).trimEnd('/')
            } else {
                pattern.substringBeforeLast('/', missingDelimiterValue = "")
            }
        return staticPrefix.ifEmpty { "(default)" }
    }

    private class ClassEntryCollector : ClassVisitor(Opcodes.ASM9) {
        var internalName: String? = null
        val methods = mutableListOf<MethodEntry>()

        override fun visit(
            version: Int,
            access: Int,
            name: String?,
            signature: String?,
            superName: String?,
            interfaces: Array<out String>?,
        ) {
            internalName = name
        }

        override fun visitMethod(
            access: Int,
            name: String,
            descriptor: String,
            signature: String?,
            exceptions: Array<out String>?,
        ): MethodVisitor? {
            methods += MethodEntry(name = name, descriptor = descriptor)
            return null
        }
    }

    private data class MethodEntry(
        val name: String,
        val descriptor: String,
    )

    private data class ReportableBaselineRule(
        val displayName: String,
        val packagePrefix: String,
        val classFlags: String,
        val methodFlags: String,
        val rule: BaselineRule,
    )

    private data class ProfileEntry(
        val rule: ReportableBaselineRule,
    )
}
