package com.lomo.baseline

import org.gradle.api.DefaultTask
import org.gradle.api.file.Directory
import org.gradle.api.file.RegularFile
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.objectweb.asm.ClassReader
import org.objectweb.asm.ClassVisitor
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes
import java.io.InputStream
import java.util.jar.JarFile

@CacheableTask
abstract class StaticBaselineProfileTask : DefaultTask() {
    @get:Input
    abstract val projectDirPath: Property<String>

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val allJars: ListProperty<RegularFile>

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val allDirs: ListProperty<Directory>

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val rulesFile: RegularFileProperty

    @get:OutputFile
    abstract val outputProfile: RegularFileProperty

    @TaskAction
    fun generate() {
        val resolvedRulesFile = resolveFile(rulesFile.get().asFile, mustExist = true)
        val rules = BaselineRule.parse(resolvedRulesFile.readText())
        require(rules.isNotEmpty()) { "Baseline rules file is empty: $resolvedRulesFile" }

        val entries = sortedSetOf<String>()
        allJars.get().forEach { jar ->
            JarFile(resolveFile(jar.asFile, mustExist = true)).use { jarFile ->
                jarFile.entries().asSequence()
                    .filter { !it.isDirectory && it.name.endsWith(".class") }
                    .forEach { entry ->
                        jarFile.getInputStream(entry).use { stream ->
                            processClass(stream, rules, entries)
                        }
                    }
            }
        }
        allDirs.get().forEach { dir ->
            resolveFile(dir.asFile, mustExist = true).walkTopDown()
                .filter { it.isFile && it.extension == "class" }
                .forEach { classFile ->
                    classFile.inputStream().use { stream ->
                        processClass(stream, rules, entries)
                    }
                }
        }

        val outputFile = resolveFile(outputProfile.get().asFile, mustExist = false)
        outputFile.parentFile.mkdirs()
        outputFile.bufferedWriter().use { writer ->
            writer.appendLine("# Generated by static baseline profile task.")
            entries.forEach(writer::appendLine)
        }
    }

    private fun resolveFile(
        file: java.io.File,
        mustExist: Boolean,
    ): java.io.File {
        if (file.exists() || !file.isAbsolute) {
            return file
        }

        val configuredProjectDir = java.io.File(projectDirPath.get()).absoluteFile.toPath()
        val filePath = file.absoluteFile.toPath()
        if (!filePath.startsWith(configuredProjectDir)) {
            return file
        }

        val fallback = configuredProjectDir.resolve(configuredProjectDir.relativize(filePath)).toFile()
        return if (!mustExist || fallback.exists()) fallback else file
    }

    private fun processClass(
        stream: InputStream,
        rules: List<BaselineRule>,
        entries: MutableSet<String>,
    ) {
        val collector = ClassEntryCollector()
        ClassReader(stream).accept(collector, ClassReader.SKIP_FRAMES or ClassReader.SKIP_DEBUG or ClassReader.SKIP_CODE)
        val internalName = collector.internalName ?: return
        val rule = rules.firstOrNull { it.matches(internalName) } ?: return

        if (rule.classFlags.isNotEmpty()) {
            entries += "${rule.classFlags}$internalName;"
        }
        collector.methods.forEach { method ->
            entries += "${rule.methodFlags}$internalName;->${method.name}${method.descriptor}"
        }
    }

    private class ClassEntryCollector : ClassVisitor(Opcodes.ASM9) {
        var internalName: String? = null
        val methods = mutableListOf<MethodEntry>()

        override fun visit(
            version: Int,
            access: Int,
            name: String?,
            signature: String?,
            superName: String?,
            interfaces: Array<out String>?,
        ) {
            internalName = name
        }

        override fun visitMethod(
            access: Int,
            name: String,
            descriptor: String,
            signature: String?,
            exceptions: Array<out String>?,
        ): MethodVisitor? {
            methods += MethodEntry(name = name, descriptor = descriptor)
            return null
        }
    }

    private data class MethodEntry(
        val name: String,
        val descriptor: String,
    )
}
