[package]
name = "demo"

[targets.apple]
enabled = true
deployment_target = "16.0"
include_macos = true

[targets.apple.swift]
module_name = "BenchBoltFFI"
output = "../../benchmarks/generated/boltffi/bindings/swift"
tools_version = "5.9"

[targets.apple.experimental]
tuple_storage = false

[targets.apple.xcframework]
output = "../../benchmarks/generated/boltffi/BoltFFIPackage"

[targets.apple.spm]
output = "../../benchmarks/generated/boltffi/BoltFFIPackage"
distribution = "local"
layout = "bundled"

[targets.android]
enabled = true
min_sdk = 24

[targets.android.kotlin]
package = "com.example.bench_boltffi"
output = "../../benchmarks/generated/boltffi/dist/android/kotlin"
factory_style = "constructors"

[targets.android.pack]
output = "../../benchmarks/generated/boltffi/dist/android/jniLibs"

[targets.wasm]
enabled = true

[targets.wasm.typescript]
output = "../../benchmarks/generated/boltffi/dist/wasm/generated"
runtime_package = "@boltffi/runtime"
runtime_version = "file:../../../runtime/typescript"

[targets.wasm.optimize]
enabled = true

[targets.wasm.npm]
output = "../../benchmarks/generated/boltffi/dist/wasm/pkg"
package_name = "@boltffi/bench"
targets = ["nodejs"]

[targets.java]
package = "com.example.bench_boltffi"
module_name = "BenchBoltFFI"

[targets.java.jvm]
enabled = true
output = "../../benchmarks/generated/boltffi/dist/java"
host_targets = ["current"]

[targets.csharp]
enabled = true
output = "../../benchmarks/generated/boltffi/dist/csharp"

[targets.python]
enabled = true
output = "../../benchmarks/generated/boltffi/dist/python"
